@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.vfyjxf.recipegraphs.ingredient.converter;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;